const placeToStayData = [
    {
        image: './images/nft15.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft16.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft17.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft18.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft11.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft12.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft13.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft14.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft21.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft22.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft23.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft24.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft25.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft26.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft27.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
    {
        image: './images/nft28.png',
        name: 'Desert king',
        perNight: '1MBT per night',
        distance: '2345km away',
        availability: 'available for 2weeks stay',
    },
]

export default placeToStayData